// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pinecone.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Db_data.Namespaces.Item.Documents.Upsert
{
    /// <summary>
    /// Builds and executes requests for operations under \db_data\namespaces\{namespaceValue}\documents\upsert
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UpsertRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_data.Namespaces.Item.Documents.Upsert.UpsertRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpsertRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/db_data/namespaces/{namespaceValue}/documents/upsert", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_data.Namespaces.Item.Documents.Upsert.UpsertRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UpsertRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/db_data/namespaces/{namespaceValue}/documents/upsert", rawUrl)
        {
        }
        /// <summary>
        /// Upsert documents into a namespace.Each document must include an `_id` field and at least one field defined in the index schema; metadata fields may beprovided alongside them.Any metadata field you provide that is not declared in the schema is stored on the document, returned via include_fields, andautomatically indexed for filtering.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.UpsertDocumentsResponse"/></returns>
        /// <param name="body">The request for the `upsert_documents` operation.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbData202607ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbData202607ErrorResponse">When receiving a 4XX or 5XX status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Pinecone.OpenApiClient.Models.UpsertDocumentsResponse?> PostAsync(global::Soenneker.Pinecone.OpenApiClient.Models.UpsertDocumentsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Pinecone.OpenApiClient.Models.UpsertDocumentsResponse> PostAsync(global::Soenneker.Pinecone.OpenApiClient.Models.UpsertDocumentsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Pinecone.OpenApiClient.Models.DbData202607ErrorResponse.CreateFromDiscriminatorValue },
                { "XXX", global::Soenneker.Pinecone.OpenApiClient.Models.DbData202607ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Pinecone.OpenApiClient.Models.UpsertDocumentsResponse>(requestInfo, global::Soenneker.Pinecone.OpenApiClient.Models.UpsertDocumentsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Upsert documents into a namespace.Each document must include an `_id` field and at least one field defined in the index schema; metadata fields may beprovided alongside them.Any metadata field you provide that is not declared in the schema is stored on the document, returned via include_fields, andautomatically indexed for filtering.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request for the `upsert_documents` operation.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Pinecone.OpenApiClient.Models.UpsertDocumentsRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Pinecone.OpenApiClient.Models.UpsertDocumentsRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_data.Namespaces.Item.Documents.Upsert.UpsertRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Pinecone.OpenApiClient.Db_data.Namespaces.Item.Documents.Upsert.UpsertRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Pinecone.OpenApiClient.Db_data.Namespaces.Item.Documents.Upsert.UpsertRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
