// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pinecone.OpenApiClient.Db_control.Collections.Item;
using Soenneker.Pinecone.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Db_control.Collections
{
    /// <summary>
    /// Builds and executes requests for operations under \db_control\collections
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CollectionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Pinecone.OpenApiClient.db_control.collections.item collection</summary>
        /// <param name="position">The name of the collection to be described.</param>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_control.Collections.Item.WithCollectionNameItemRequestBuilder"/></returns>
        public global::Soenneker.Pinecone.OpenApiClient.Db_control.Collections.Item.WithCollectionNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("collectionName", position);
                return new global::Soenneker.Pinecone.OpenApiClient.Db_control.Collections.Item.WithCollectionNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_control.Collections.CollectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/db_control/collections", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_control.Collections.CollectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/db_control/collections", rawUrl)
        {
        }
        /// <summary>
        /// List all collections in a project.Serverless indexes do not support collections.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.CollectionList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Pinecone.OpenApiClient.Models.CollectionList?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Pinecone.OpenApiClient.Models.CollectionList> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Pinecone.OpenApiClient.Models.CollectionList>(requestInfo, global::Soenneker.Pinecone.OpenApiClient.Models.CollectionList.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a Pinecone collection.  Serverless indexes do not support collections.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.CollectionModel"/></returns>
        /// <param name="body">The configuration needed to create a Pinecone collection.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse">When receiving a 402 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse">When receiving a 409 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Pinecone.OpenApiClient.Models.CollectionModel?> PostAsync(global::Soenneker.Pinecone.OpenApiClient.Models.CreateCollectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Pinecone.OpenApiClient.Models.CollectionModel> PostAsync(global::Soenneker.Pinecone.OpenApiClient.Models.CreateCollectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse.CreateFromDiscriminatorValue },
                { "402", global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse.CreateFromDiscriminatorValue },
                { "409", global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Pinecone.OpenApiClient.Models.DbControl202604ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Pinecone.OpenApiClient.Models.CollectionModel>(requestInfo, global::Soenneker.Pinecone.OpenApiClient.Models.CollectionModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// List all collections in a project.Serverless indexes do not support collections.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a Pinecone collection.  Serverless indexes do not support collections.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The configuration needed to create a Pinecone collection.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Pinecone.OpenApiClient.Models.CreateCollectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Pinecone.OpenApiClient.Models.CreateCollectionRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_control.Collections.CollectionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Pinecone.OpenApiClient.Db_control.Collections.CollectionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Pinecone.OpenApiClient.Db_control.Collections.CollectionsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
