// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Operations.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Operations
{
    /// <summary>
    /// Builds and executes requests for operations under \assistant_data_2026-04\operations
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OperationsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Pinecone.OpenApiClient.assistant_data_202604.operations.item collection</summary>
        /// <param name="position">The name of the assistant to list operations for.</param>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Operations.Item.WithAssistant_nameItemRequestBuilder"/></returns>
        public global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Operations.Item.WithAssistant_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("assistant_name", position);
                return new global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Operations.Item.WithAssistant_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Operations.OperationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OperationsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assistant_data_2026-04/operations", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Operations.OperationsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public OperationsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assistant_data_2026-04/operations", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
