// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pinecone.OpenApiClient.Db_data_202604.Bulk.Imports;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Db_data_202604.Bulk
{
    /// <summary>
    /// Builds and executes requests for operations under \db_data_2026-04\bulk
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BulkRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The imports property</summary>
        public global::Soenneker.Pinecone.OpenApiClient.Db_data_202604.Bulk.Imports.ImportsRequestBuilder Imports
        {
            get => new global::Soenneker.Pinecone.OpenApiClient.Db_data_202604.Bulk.Imports.ImportsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_data_202604.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/db_data_2026-04/bulk", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_data_202604.Bulk.BulkRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public BulkRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/db_data_2026-04/bulk", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
