// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// The artifact leg: knowledge an LLM distills out of the sources, as prose files or database rows. Off by default.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ArtifactsConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Model tier that does the extraction. `standard` reads more carefully at a higher token cost.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ArtifactModel { get; set; }
#nullable restore
#else
        public string ArtifactModel { get; set; }
#endif
        /// <summary>What kinds of artifact to extract. Nothing is extracted until at least one is declared.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.ArtifactType>? ArtifactTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.ArtifactType> ArtifactTypes { get; set; }
#endif
        /// <summary>Typed, directed relationships between artifact types, which turn the artifacts into a graph the agent can traverse.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.EdgeType>? EdgeTypes { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.EdgeType> EdgeTypes { get; set; }
#endif
        /// <summary>Whether curate extracts artifacts at all.</summary>
        public bool? Enabled { get; set; }
        /// <summary>Window size for walking a long source across several extraction calls, so its back half is covered rather than dropped. `0` opts out and reads only the head, up to `max_doc_chars`.</summary>
        public int? ExtractionWindowChars { get; set; }
        /// <summary>How many artifacts one type may produce. Omit for no cap.</summary>
        public int? MaxArtifactsPerType { get; set; }
        /// <summary>Input cap for one extraction call, in characters. With windowing off this also caps how much of a source is read at all; everything beyond it is dropped.</summary>
        public int? MaxDocChars { get; set; }
        /// <summary>How many mentions are fed into the pass that reduces them into one corpus-wide artifact.</summary>
        public int? MaxMentionsPerArtifact { get; set; }
        /// <summary>Output cap for one extracted artifact, in tokens.</summary>
        public int? MaxTokens { get; set; }
        /// <summary>Cap on those mentions once concatenated, in characters. Applied after `max_mentions_per_artifact`.</summary>
        public int? MentionContextChars { get; set; }
        /// <summary>Cap on one recorded mention — what a single document says about the subject — in characters.</summary>
        public int? MentionMaxChars { get; set; }
        /// <summary>How many source documents must mention a corpus-scoped subject before it earns an artifact. Raise it to suppress one-off mentions. An artifact type may override it.</summary>
        public int? MinDocCount { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ArtifactsConfig"/> and sets the default values.
        /// </summary>
        public ArtifactsConfig()
        {
            AdditionalData = new Dictionary<string, object>();
            ArtifactModel = "lite";
            Enabled = false;
            ExtractionWindowChars = 0;
            MaxArtifactsPerType = 10000;
            MaxDocChars = 60000;
            MaxMentionsPerArtifact = 40;
            MaxTokens = 1500;
            MentionContextChars = 8000;
            MentionMaxChars = 400;
            MinDocCount = 1;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ArtifactsConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.ArtifactsConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.ArtifactsConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "artifact_model", n => { ArtifactModel = n.GetStringValue(); } },
                { "artifact_types", n => { ArtifactTypes = n.GetCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.ArtifactType>(global::Soenneker.Pinecone.OpenApiClient.Models.ArtifactType.CreateFromDiscriminatorValue)?.AsList(); } },
                { "edge_types", n => { EdgeTypes = n.GetCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.EdgeType>(global::Soenneker.Pinecone.OpenApiClient.Models.EdgeType.CreateFromDiscriminatorValue)?.AsList(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "extraction_window_chars", n => { ExtractionWindowChars = n.GetIntValue(); } },
                { "max_artifacts_per_type", n => { MaxArtifactsPerType = n.GetIntValue(); } },
                { "max_doc_chars", n => { MaxDocChars = n.GetIntValue(); } },
                { "max_mentions_per_artifact", n => { MaxMentionsPerArtifact = n.GetIntValue(); } },
                { "max_tokens", n => { MaxTokens = n.GetIntValue(); } },
                { "mention_context_chars", n => { MentionContextChars = n.GetIntValue(); } },
                { "mention_max_chars", n => { MentionMaxChars = n.GetIntValue(); } },
                { "min_doc_count", n => { MinDocCount = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("artifact_model", ArtifactModel);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.ArtifactType>("artifact_types", ArtifactTypes);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.EdgeType>("edge_types", EdgeTypes);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteIntValue("extraction_window_chars", ExtractionWindowChars);
            writer.WriteIntValue("max_artifacts_per_type", MaxArtifactsPerType);
            writer.WriteIntValue("max_doc_chars", MaxDocChars);
            writer.WriteIntValue("max_mentions_per_artifact", MaxMentionsPerArtifact);
            writer.WriteIntValue("max_tokens", MaxTokens);
            writer.WriteIntValue("mention_context_chars", MentionContextChars);
            writer.WriteIntValue("mention_max_chars", MentionMaxChars);
            writer.WriteIntValue("min_doc_count", MinDocCount);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
