// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// The response format for a successful file upload request.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AssistantFileModel : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The timestamp when the file was uploaded, in ISO 8601 format (`YYYY-MM-DDTHH:MM:SSZ`).</summary>
        public DateTimeOffset? CreatedOn { get; set; }
        /// <summary>The unique identifier for the uploaded file. This may be a user-provided identifier or a system-generated ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Optional metadata associated with the file. This metadata can be used to filter files when listing them or to restrict search results when querying the assistant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.AssistantFileModel_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.AssistantFileModel_metadata Metadata { get; set; }
#endif
        /// <summary>Indicates whether the file was processed as multimodal.</summary>
        public bool? Multimodal { get; set; }
        /// <summary>The name of the uploaded file.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>A [signed URL](https://cloud.google.com/storage/docs/access-control/signed-urls) that provides temporary, read-only access to the file.  Anyone with the link can access the file, so treat it as sensitive data. Expires after a short time.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignedUrl { get; set; }
#nullable restore
#else
        public string SignedUrl { get; set; }
#endif
        /// <summary>The size of the uploaded file, in bytes.</summary>
        public long? Size { get; set; }
        /// <summary>&quot;The current state of the uploaded file. Possible values:- `Processing`: File is being processed (parsed, chunked, embedded)- `Available`: Processing completed successfully; file is ready for use- `Deleting`: Deletion has been initiated but not yet completed- `ProcessingFailed`: Processing failed with an errorNote: Once a file is deleted, the API returns 404 Not Found instead of a file object.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The timestamp of the most recent update to the file, in ISO 8601 format (`YYYY-MM-DDTHH:MM:SSZ`).</summary>
        public DateTimeOffset? UpdatedOn { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.AssistantFileModel"/> and sets the default values.
        /// </summary>
        public AssistantFileModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.AssistantFileModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.AssistantFileModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.AssistantFileModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "created_on", n => { CreatedOn = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.AssistantFileModel_metadata>(global::Soenneker.Pinecone.OpenApiClient.Models.AssistantFileModel_metadata.CreateFromDiscriminatorValue); } },
                { "multimodal", n => { Multimodal = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "signed_url", n => { SignedUrl = n.GetStringValue(); } },
                { "size", n => { Size = n.GetLongValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "updated_on", n => { UpdatedOn = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("created_on", CreatedOn);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.AssistantFileModel_metadata>("metadata", Metadata);
            writer.WriteBoolValue("multimodal", Multimodal);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("signed_url", SignedUrl);
            writer.WriteLongValue("size", Size);
            writer.WriteStringValue("status", Status);
            writer.WriteDateTimeOffsetValue("updated_on", UpdatedOn);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
