// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// The BackupModel describes the configuration and status of a Pinecone backup.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class BackupModel : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Unique identifier for the backup.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BackupId { get; set; }
#nullable restore
#else
        public string BackupId { get; set; }
#endif
        /// <summary>Cloud provider where the backup is stored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cloud { get; set; }
#nullable restore
#else
        public string Cloud { get; set; }
#endif
        /// <summary>Timestamp when the backup was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Optional description providing context for the backup.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>Optional user-defined name for the backup.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Number of namespaces in the backup.</summary>
        public long? NamespaceCount { get; set; }
        /// <summary>Total number of records in the backup.</summary>
        public long? RecordCount { get; set; }
        /// <summary>Cloud region where the backup is stored.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Region { get; set; }
#nullable restore
#else
        public string Region { get; set; }
#endif
        /// <summary>The schema of a Pinecone index. The schema defines the typed fields that documents in the index can contain, including vector fields, semantic text fields, and metadata fields.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.IndexSchema? Schema { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.IndexSchema Schema { get; set; }
#endif
        /// <summary>Size of the backup in bytes.</summary>
        public long? SizeBytes { get; set; }
        /// <summary>The deletion timestamp when the source index has been deleted. Not present for backups associated with an active index.</summary>
        public DateTimeOffset? SourceIndexDeletedAt { get; set; }
        /// <summary>ID of the index from which the backup was taken.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceIndexId { get; set; }
#nullable restore
#else
        public string SourceIndexId { get; set; }
#endif
        /// <summary>Name of the index from which the backup was taken.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SourceIndexName { get; set; }
#nullable restore
#else
        public string SourceIndexName { get; set; }
#endif
        /// <summary>Current status of the backup.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Custom user tags added to an index, at most 20 per index. Keys must be 80 characters or less and alphanumeric, &apos;_&apos;, or &apos;-&apos;. Values must be 120 characters or less and consist of printable ASCII characters or spaces. To unset a key, set the value to be an empty string. `null` in responses when the index has no tags.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.BackupModelTags? Tags { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.BackupModelTags Tags { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.BackupModel"/> and sets the default values.
        /// </summary>
        public BackupModel()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.BackupModel"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.BackupModel CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.BackupModel();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "backup_id", n => { BackupId = n.GetStringValue(); } },
                { "cloud", n => { Cloud = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "namespace_count", n => { NamespaceCount = n.GetLongValue(); } },
                { "record_count", n => { RecordCount = n.GetLongValue(); } },
                { "region", n => { Region = n.GetStringValue(); } },
                { "schema", n => { Schema = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.IndexSchema>(global::Soenneker.Pinecone.OpenApiClient.Models.IndexSchema.CreateFromDiscriminatorValue); } },
                { "size_bytes", n => { SizeBytes = n.GetLongValue(); } },
                { "source_index_deleted_at", n => { SourceIndexDeletedAt = n.GetDateTimeOffsetValue(); } },
                { "source_index_id", n => { SourceIndexId = n.GetStringValue(); } },
                { "source_index_name", n => { SourceIndexName = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.BackupModelTags>(global::Soenneker.Pinecone.OpenApiClient.Models.BackupModelTags.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("backup_id", BackupId);
            writer.WriteStringValue("cloud", Cloud);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("name", Name);
            writer.WriteLongValue("namespace_count", NamespaceCount);
            writer.WriteLongValue("record_count", RecordCount);
            writer.WriteStringValue("region", Region);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.IndexSchema>("schema", Schema);
            writer.WriteLongValue("size_bytes", SizeBytes);
            writer.WriteDateTimeOffsetValue("source_index_deleted_at", SourceIndexDeletedAt);
            writer.WriteStringValue("source_index_id", SourceIndexId);
            writer.WriteStringValue("source_index_name", SourceIndexName);
            writer.WriteStringValue("status", Status);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.BackupModelTags>("tags", Tags);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
