// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>Identifies this as a BYOC deployment. Must be `byoc`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ByocDeploymentType
    {
        [EnumMember(Value = "byoc")]
        #pragma warning disable CS1591
        Byoc,
        #pragma warning restore CS1591
    }
}
