// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ConfigureIndexRequestSpecServerless : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Updated configuration for serverless indexes</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ConfigureIndexRequestSpecServerlessServerless? Serverless { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ConfigureIndexRequestSpecServerlessServerless Serverless { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ConfigureIndexRequestSpecServerless"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.ConfigureIndexRequestSpecServerless CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.ConfigureIndexRequestSpecServerless();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "serverless", n => { Serverless = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ConfigureIndexRequestSpecServerlessServerless>(global::Soenneker.Pinecone.OpenApiClient.Models.ConfigureIndexRequestSpecServerlessServerless.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ConfigureIndexRequestSpecServerlessServerless>("serverless", Serverless);
        }
    }
}
#pragma warning restore CS0618
