// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// Request body for creating a backup schedule on an index.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CreateBackupScheduleRequest : IParsable
    {
        /// <summary>User-defined name for the backup schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Retention policy for backups created by this schedule. Backups older than the retention window may be removed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.BackupScheduleRetentionInput? Retention { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.BackupScheduleRetentionInput Retention { get; set; }
#endif
        /// <summary>Time-based schedule configuration for automatic index backups. Only time-based schedules are supported.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.BackupScheduleRequestSchedule? Schedule { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.BackupScheduleRequestSchedule Schedule { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.CreateBackupScheduleRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.CreateBackupScheduleRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.CreateBackupScheduleRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "name", n => { Name = n.GetStringValue(); } },
                { "retention", n => { Retention = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.BackupScheduleRetentionInput>(global::Soenneker.Pinecone.OpenApiClient.Models.BackupScheduleRetentionInput.CreateFromDiscriminatorValue); } },
                { "schedule", n => { Schedule = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.BackupScheduleRequestSchedule>(global::Soenneker.Pinecone.OpenApiClient.Models.BackupScheduleRequestSchedule.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.BackupScheduleRetentionInput>("retention", Retention);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.BackupScheduleRequestSchedule>("schedule", Schedule);
        }
    }
}
#pragma warning restore CS0618
