// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>Identifies this as a dense vector field. Must be `dense_vector`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DenseVectorType
    {
        [EnumMember(Value = "dense_vector")]
        #pragma warning disable CS1591
        DenseVector,
        #pragma warning restore CS1591
    }
}
