// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// The response for the `fetch_by_metadata` operation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class FetchByMetadataResponse : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The namespace of the vectors.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Namespace { get; set; }
#nullable restore
#else
        public string Namespace { get; set; }
#endif
        /// <summary>The pagination property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.Pagination? Pagination { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.Pagination Pagination { get; set; }
#endif
        /// <summary>The usage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.Usage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.Usage Usage { get; set; }
#endif
        /// <summary>The fetched vectors, in the form of a map between the fetched ids and the fetched vectors</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.FetchByMetadataResponseVectorsProperty? Vectors { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.FetchByMetadataResponseVectorsProperty Vectors { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.FetchByMetadataResponse"/> and sets the default values.
        /// </summary>
        public FetchByMetadataResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.FetchByMetadataResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.FetchByMetadataResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.FetchByMetadataResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "namespace", n => { Namespace = n.GetStringValue(); } },
                { "pagination", n => { Pagination = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.Pagination>(global::Soenneker.Pinecone.OpenApiClient.Models.Pagination.CreateFromDiscriminatorValue); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.Usage>(global::Soenneker.Pinecone.OpenApiClient.Models.Usage.CreateFromDiscriminatorValue); } },
                { "vectors", n => { Vectors = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.FetchByMetadataResponseVectorsProperty>(global::Soenneker.Pinecone.OpenApiClient.Models.FetchByMetadataResponseVectorsProperty.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("namespace", Namespace);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.Pagination>("pagination", Pagination);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.Usage>("usage", Usage);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.FetchByMetadataResponseVectorsProperty>("vectors", Vectors);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
