// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// What an import staged. Staging only — the sources are not indexed until a curate runs.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ImportOutput : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Records that could not be ingested.</summary>
        public long? Failed { get; set; }
        /// <summary>Records pulled from the provider.</summary>
        public long? ImportedItems { get; set; }
        /// <summary>Where the full manifest was written</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ManifestFile { get; set; }
#nullable restore
#else
        public string ManifestFile { get; set; }
#endif
        /// <summary>Object-store key of the full manifest</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ManifestObject { get; set; }
#nullable restore
#else
        public string ManifestObject { get; set; }
#endif
        /// <summary>Bounded sample of the records that produced output</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.ImportManifestEntry>? ManifestSample { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.ImportManifestEntry> ManifestSample { get; set; }
#endif
        /// <summary>Whether either sample was cut</summary>
        public bool? ManifestTruncated { get; set; }
        /// <summary>Files written into the source tree. Higher than `imported_items` when archives or multi-page documents expanded.</summary>
        public long? OutputFiles { get; set; }
        /// <summary>Records passed over, e.g. an unsupported extension or a cap already reached.</summary>
        public long? Skipped { get; set; }
        /// <summary>Bounded sample of the skipped records</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.ImportManifestEntry>? SkippedItems { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.ImportManifestEntry> SkippedItems { get; set; }
#endif
        /// <summary>How the run ended.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ImportOutput"/> and sets the default values.
        /// </summary>
        public ImportOutput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ImportOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.ImportOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.ImportOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "failed", n => { Failed = n.GetLongValue(); } },
                { "imported_items", n => { ImportedItems = n.GetLongValue(); } },
                { "manifest_file", n => { ManifestFile = n.GetStringValue(); } },
                { "manifest_object", n => { ManifestObject = n.GetStringValue(); } },
                { "manifest_sample", n => { ManifestSample = n.GetCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.ImportManifestEntry>(global::Soenneker.Pinecone.OpenApiClient.Models.ImportManifestEntry.CreateFromDiscriminatorValue)?.AsList(); } },
                { "manifest_truncated", n => { ManifestTruncated = n.GetBoolValue(); } },
                { "output_files", n => { OutputFiles = n.GetLongValue(); } },
                { "skipped", n => { Skipped = n.GetLongValue(); } },
                { "skipped_items", n => { SkippedItems = n.GetCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.ImportManifestEntry>(global::Soenneker.Pinecone.OpenApiClient.Models.ImportManifestEntry.CreateFromDiscriminatorValue)?.AsList(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("failed", Failed);
            writer.WriteLongValue("imported_items", ImportedItems);
            writer.WriteStringValue("manifest_file", ManifestFile);
            writer.WriteStringValue("manifest_object", ManifestObject);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.ImportManifestEntry>("manifest_sample", ManifestSample);
            writer.WriteBoolValue("manifest_truncated", ManifestTruncated);
            writer.WriteLongValue("output_files", OutputFiles);
            writer.WriteLongValue("skipped", Skipped);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.ImportManifestEntry>("skipped_items", SkippedItems);
            writer.WriteStringValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
