// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// The response for the `describe_index_stats` operation.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class IndexDescription : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The dimension of the indexed vectors. Not specified if `sparse` index.</summary>
        public long? Dimension { get; set; }
        /// <summary>The fullness of the index, regardless of whether a metadata filter expression was passed. The granularity of this metric is 10%.Serverless indexes scale automatically as needed, so index fullness  is relevant only for pod-based indexes.The index fullness result may be inaccurate during pod resizing; to get the status of a pod resizing process, use [`describe_index`](https://docs.pinecone.io/reference/api/2024-10/control-plane/describe_index).</summary>
        public float? IndexFullness { get; set; }
        /// <summary>The amount of memory used by a dedicated index</summary>
        public float? MemoryFullness { get; set; }
        /// <summary>The metric used to measure similarity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metric { get; set; }
#nullable restore
#else
        public string Metric { get; set; }
#endif
        /// <summary>A mapping for each namespace in the index from the namespace name to a summary of its contents. If a metadata filter expression is present, the summary will reflect only vectors matching that expression.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.IndexDescriptionNamespacesProperty? Namespaces { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.IndexDescriptionNamespacesProperty Namespaces { get; set; }
#endif
        /// <summary>The amount of storage used by a dedicated index</summary>
        public float? StorageFullness { get; set; }
        /// <summary>The total number of vectors in the index, regardless of whether a metadata filter expression was passed</summary>
        public long? TotalVectorCount { get; set; }
        /// <summary>The type of vectors stored in the index.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? VectorType { get; set; }
#nullable restore
#else
        public string VectorType { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.IndexDescription"/> and sets the default values.
        /// </summary>
        public IndexDescription()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.IndexDescription"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.IndexDescription CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.IndexDescription();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "dimension", n => { Dimension = n.GetLongValue(); } },
                { "indexFullness", n => { IndexFullness = n.GetFloatValue(); } },
                { "memory_fullness", n => { MemoryFullness = n.GetFloatValue(); } },
                { "metric", n => { Metric = n.GetStringValue(); } },
                { "namespaces", n => { Namespaces = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.IndexDescriptionNamespacesProperty>(global::Soenneker.Pinecone.OpenApiClient.Models.IndexDescriptionNamespacesProperty.CreateFromDiscriminatorValue); } },
                { "storage_fullness", n => { StorageFullness = n.GetFloatValue(); } },
                { "totalVectorCount", n => { TotalVectorCount = n.GetLongValue(); } },
                { "vectorType", n => { VectorType = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("dimension", Dimension);
            writer.WriteFloatValue("indexFullness", IndexFullness);
            writer.WriteFloatValue("memory_fullness", MemoryFullness);
            writer.WriteStringValue("metric", Metric);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.IndexDescriptionNamespacesProperty>("namespaces", Namespaces);
            writer.WriteFloatValue("storage_fullness", StorageFullness);
            writer.WriteLongValue("totalVectorCount", TotalVectorCount);
            writer.WriteStringValue("vectorType", VectorType);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
