// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// Scheduled self-tuning config.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OptimizeManifest : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The eval_pass_rate_threshold property</summary>
        public double? EvalPassRateThreshold { get; set; }
        /// <summary>The latency_threshold_ms property</summary>
        public int? LatencyThresholdMs { get; set; }
        /// <summary>The max_iterations property</summary>
        public int? MaxIterations { get; set; }
        /// <summary>The min_group_size property</summary>
        public int? MinGroupSize { get; set; }
        /// <summary>cron</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Schedule { get; set; }
#nullable restore
#else
        public string Schedule { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeManifest"/> and sets the default values.
        /// </summary>
        public OptimizeManifest()
        {
            AdditionalData = new Dictionary<string, object>();
            EvalPassRateThreshold = 1;
            LatencyThresholdMs = 60000;
            MaxIterations = 20;
            MinGroupSize = 2;
            Schedule = "0 * * * *";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeManifest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeManifest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeManifest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "eval_pass_rate_threshold", n => { EvalPassRateThreshold = n.GetDoubleValue(); } },
                { "latency_threshold_ms", n => { LatencyThresholdMs = n.GetIntValue(); } },
                { "max_iterations", n => { MaxIterations = n.GetIntValue(); } },
                { "min_group_size", n => { MinGroupSize = n.GetIntValue(); } },
                { "schedule", n => { Schedule = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("eval_pass_rate_threshold", EvalPassRateThreshold);
            writer.WriteIntValue("latency_threshold_ms", LatencyThresholdMs);
            writer.WriteIntValue("max_iterations", MaxIterations);
            writer.WriteIntValue("min_group_size", MinGroupSize);
            writer.WriteStringValue("schedule", Schedule);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
