// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// What the tuning loop settled on.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class OptimizeResultOutput : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Which iteration scored it.</summary>
        public long? BestIteration { get; set; }
        /// <summary>Whether that iteration also stayed under the latency bar.</summary>
        public bool? BestLatencyOk { get; set; }
        /// <summary>Eval pass rate the best iteration scored, 0–1.</summary>
        public double? BestScore { get; set; }
        /// <summary>Which manifest legs the tuning changed, so a re-curate can be scoped to them.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ChangedLegs { get; set; }
#nullable restore
#else
        public List<string> ChangedLegs { get; set; }
#endif
        /// <summary>Wall time for the whole loop.</summary>
        public double? ElapsedSeconds { get; set; }
        /// <summary>The tuned manifest persisted onto the context when the task completes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutputManifest? Manifest { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutputManifest Manifest { get; set; }
#endif
        /// <summary>Tier → resolved model id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutputModelsProperty? Models { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutputModelsProperty Models { get; set; }
#endif
        /// <summary>The p90 latency bar. Null when latency was not gated.</summary>
        public double? P90LatencyLimitMs { get; set; }
        /// <summary>The pass-rate bar the run measured against.</summary>
        public double? PassRateThreshold { get; set; }
        /// <summary>Set to `ready` only when the best iteration cleared both the pass-rate and latency bars.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Candidate manifests tried.</summary>
        public long? TotalIterations { get; set; }
        /// <summary>Model selections dropped as unknown before dispatch, so a caller whose pin was silently ignored can see it. Absent when nothing was dropped.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? UnknownModels { get; set; }
#nullable restore
#else
        public List<string> UnknownModels { get; set; }
#endif
        /// <summary>What a run billed on the chat seam, in tokens. Reported by the inference client, which carries the cache-token fields. Used by optimize and explore.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ChatUsage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ChatUsage Usage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutput"/> and sets the default values.
        /// </summary>
        public OptimizeResultOutput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "best_iteration", n => { BestIteration = n.GetLongValue(); } },
                { "best_latency_ok", n => { BestLatencyOk = n.GetBoolValue(); } },
                { "best_score", n => { BestScore = n.GetDoubleValue(); } },
                { "changed_legs", n => { ChangedLegs = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "elapsed_seconds", n => { ElapsedSeconds = n.GetDoubleValue(); } },
                { "manifest", n => { Manifest = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutputManifest>(global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutputManifest.CreateFromDiscriminatorValue); } },
                { "models", n => { Models = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutputModelsProperty>(global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutputModelsProperty.CreateFromDiscriminatorValue); } },
                { "p90_latency_limit_ms", n => { P90LatencyLimitMs = n.GetDoubleValue(); } },
                { "pass_rate_threshold", n => { PassRateThreshold = n.GetDoubleValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "total_iterations", n => { TotalIterations = n.GetLongValue(); } },
                { "unknown_models", n => { UnknownModels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ChatUsage>(global::Soenneker.Pinecone.OpenApiClient.Models.ChatUsage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("best_iteration", BestIteration);
            writer.WriteBoolValue("best_latency_ok", BestLatencyOk);
            writer.WriteDoubleValue("best_score", BestScore);
            writer.WriteCollectionOfPrimitiveValues<string>("changed_legs", ChangedLegs);
            writer.WriteDoubleValue("elapsed_seconds", ElapsedSeconds);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutputManifest>("manifest", Manifest);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutputModelsProperty>("models", Models);
            writer.WriteDoubleValue("p90_latency_limit_ms", P90LatencyLimitMs);
            writer.WriteDoubleValue("pass_rate_threshold", PassRateThreshold);
            writer.WriteStringValue("status", Status);
            writer.WriteLongValue("total_iterations", TotalIterations);
            writer.WriteCollectionOfPrimitiveValues<string>("unknown_models", UnknownModels);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ChatUsage>("usage", Usage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
