// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// Deployment configuration for a pod-based index.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PodDeployment : IParsable
    {
        /// <summary>Identifies this as a pod-based deployment. Must be `pod`.</summary>
        public global::Soenneker.Pinecone.OpenApiClient.Models.PodDeploymentType? DeploymentType { get; set; }
        /// <summary>The environment where the index is hosted.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Environment { get; set; }
#nullable restore
#else
        public string Environment { get; set; }
#endif
        /// <summary>The type of pod to use. One of `s1`, `p1`, or `p2` appended with `.` and one of `x1`, `x2`, `x4`, or `x8`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PodType { get; set; }
#nullable restore
#else
        public string PodType { get; set; }
#endif
        /// <summary>The number of replicas. Replicas duplicate your index. They provide higher availability and throughput. Replicas can be scaled up or down as your needs change.</summary>
        public int? Replicas { get; set; }
        /// <summary>The number of shards. Shards split your data across multiple pods so you can fit more data into an index.</summary>
        public int? Shards { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.PodDeployment"/> and sets the default values.
        /// </summary>
        public PodDeployment()
        {
            PodType = "p1.x1";
            Replicas = 1;
            Shards = 1;
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.PodDeployment"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.PodDeployment CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.PodDeployment();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "deployment_type", n => { DeploymentType = n.GetEnumValue<global::Soenneker.Pinecone.OpenApiClient.Models.PodDeploymentType>(); } },
                { "environment", n => { Environment = n.GetStringValue(); } },
                { "pod_type", n => { PodType = n.GetStringValue(); } },
                { "replicas", n => { Replicas = n.GetIntValue(); } },
                { "shards", n => { Shards = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Pinecone.OpenApiClient.Models.PodDeploymentType>("deployment_type", DeploymentType);
            writer.WriteStringValue("environment", Environment);
            writer.WriteStringValue("pod_type", PodType);
            writer.WriteIntValue("replicas", Replicas);
            writer.WriteIntValue("shards", Shards);
        }
    }
}
#pragma warning restore CS0618
