// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// One estimate per model tier.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProfileEstimateOutputCostByTier : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>What the curate would cost at one model tier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost? Lite { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost Lite { get; set; }
#endif
        /// <summary>What the curate would cost at one model tier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost? Pro { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost Pro { get; set; }
#endif
        /// <summary>What the curate would cost at one model tier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost? Standard { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost Standard { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEstimateOutputCostByTier"/> and sets the default values.
        /// </summary>
        public ProfileEstimateOutputCostByTier()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEstimateOutputCostByTier"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEstimateOutputCostByTier CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEstimateOutputCostByTier();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "lite", n => { Lite = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost>(global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost.CreateFromDiscriminatorValue); } },
                { "pro", n => { Pro = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost>(global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost.CreateFromDiscriminatorValue); } },
                { "standard", n => { Standard = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost>(global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost>("lite", Lite);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost>("pro", Pro);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ProfileTierCost>("standard", Standard);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
