// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// Aggregate task counters for the whole project.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ProjectTaskStats : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>When the counters were read.</summary>
        public DateTimeOffset? CapturedAt { get; set; }
        /// <summary>Tasks in a non-terminal state.</summary>
        public int? TasksActive { get; set; }
        /// <summary>Keyed by `TaskState`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStatsTasksByStateProperty? TasksByState { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStatsTasksByStateProperty TasksByState { get; set; }
#endif
        /// <summary>Keyed by `Workflow`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStatsTasksByWorkflowProperty? TasksByWorkflow { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStatsTasksByWorkflowProperty TasksByWorkflow { get; set; }
#endif
        /// <summary>Runs stopped before they finished.</summary>
        public int? TasksCancelled { get; set; }
        /// <summary>Tasks that finished successfully.</summary>
        public int? TasksCompleted { get; set; }
        /// <summary>Tasks the project has ever run.</summary>
        public int? TasksTotal { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStats"/> and sets the default values.
        /// </summary>
        public ProjectTaskStats()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStats"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStats CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStats();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "captured_at", n => { CapturedAt = n.GetDateTimeOffsetValue(); } },
                { "tasks_active", n => { TasksActive = n.GetIntValue(); } },
                { "tasks_by_state", n => { TasksByState = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStatsTasksByStateProperty>(global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStatsTasksByStateProperty.CreateFromDiscriminatorValue); } },
                { "tasks_by_workflow", n => { TasksByWorkflow = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStatsTasksByWorkflowProperty>(global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStatsTasksByWorkflowProperty.CreateFromDiscriminatorValue); } },
                { "tasks_cancelled", n => { TasksCancelled = n.GetIntValue(); } },
                { "tasks_completed", n => { TasksCompleted = n.GetIntValue(); } },
                { "tasks_total", n => { TasksTotal = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("captured_at", CapturedAt);
            writer.WriteIntValue("tasks_active", TasksActive);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStatsTasksByStateProperty>("tasks_by_state", TasksByState);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ProjectTaskStatsTasksByWorkflowProperty>("tasks_by_workflow", TasksByWorkflow);
            writer.WriteIntValue("tasks_cancelled", TasksCancelled);
            writer.WriteIntValue("tasks_completed", TasksCompleted);
            writer.WriteIntValue("tasks_total", TasksTotal);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
