// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum QueryStringType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "query_string")]
        #pragma warning disable CS1591
        QueryString,
        #pragma warning restore CS1591
    }
}
