// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// One query turn. Read the answer from `output[].content[].text`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Query : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>What the answer was grounded in. Empty on a turn that cited nothing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.Citation>? Citations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.Citation> Citations { get; set; }
#endif
        /// <summary>The sibling turns of the same Compare run. Null on a normal single query.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.QueryComparisonMember>? Comparison { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.QueryComparisonMember> Comparison { get; set; }
#endif
        /// <summary>Unix seconds</summary>
        public long? Created { get; set; }
        /// <summary>Failure detail. Set on a `failed` turn.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>Thumbs-up/down recorded on this turn. Null until a caller submits some.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.QueryFeedback? Feedback { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.QueryFeedback Feedback { get; set; }
#endif
        /// <summary>Turn id, `qry_&lt;uuid&gt;`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The stored message array (plain-text `content`).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.QueryInputItem>? Input { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.QueryInputItem> Input { get; set; }
#endif
        /// <summary>The agentic tool-loop step cap this turn actually ran with, whether the request set it or the deployment default supplied it.</summary>
        public long? MaxSteps { get; set; }
        /// <summary>The model that actually answered. Null before the turn resolves one.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>Always `query`, so a caller can tell this document apart from a session.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Object { get; set; }
#nullable restore
#else
        public string Object { get; set; }
#endif
        /// <summary>Output items; assistant text is `{role, content:[{type: output_text, text}]}`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.QueryOutputItem>? Output { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.QueryOutputItem> Output { get; set; }
#endif
        /// <summary>Present when a shape was used, or on a retrieval-only turn</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.QueryOutputJsonProperty? OutputJson { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.QueryOutputJsonProperty OutputJson { get; set; }
#endif
        /// <summary>The turn this one continues. Null on a session&apos;s first turn.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PreviousQueryId { get; set; }
#nullable restore
#else
        public string PreviousQueryId { get; set; }
#endif
        /// <summary>End-of-turn counters. Null on a turn the runtime never closed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.QueryRollup? Rollup { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.QueryRollup Rollup { get; set; }
#endif
        /// <summary>Wall time from turn start to terminal state.</summary>
        public long? RuntimeMs { get; set; }
        /// <summary>The session this turn belongs to. A turn that started a new one names it here.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SessionId { get; set; }
#nullable restore
#else
        public string SessionId { get; set; }
#endif
        /// <summary>Where the turn is in its lifecycle.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>The turn&apos;s reasoning steps, reduced from its `response.step` events.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.QueryStep>? Steps { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.QueryStep> Steps { get; set; }
#endif
        /// <summary>The answer completion&apos;s cost. Null on a turn that skipped synthesis, as retrieval-only turns do.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.QuerySynthesisComposed? Synthesis { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.QuerySynthesisComposed Synthesis { get; set; }
#endif
        /// <summary>The thinking level this turn actually ran at. Null on the Claude-backed `search_cc`, which has no equivalent knob.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThinkingLevel { get; set; }
#nullable restore
#else
        public string ThinkingLevel { get; set; }
#endif
        /// <summary>Blob key of the persisted trace. Fetch the trace itself from `GET /queries/{id}/trace`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TraceRef { get; set; }
#nullable restore
#else
        public string TraceRef { get; set; }
#endif
        /// <summary>The turn&apos;s token totals. Embed and rerank bill on their own seam and are not counted here.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.QueryUsage? Usage { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.QueryUsage Usage { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.Query"/> and sets the default values.
        /// </summary>
        public Query()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.Query"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.Query CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.Query();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "citations", n => { Citations = n.GetCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.Citation>(global::Soenneker.Pinecone.OpenApiClient.Models.Citation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "comparison", n => { Comparison = n.GetCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.QueryComparisonMember>(global::Soenneker.Pinecone.OpenApiClient.Models.QueryComparisonMember.CreateFromDiscriminatorValue)?.AsList(); } },
                { "created", n => { Created = n.GetLongValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "feedback", n => { Feedback = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.QueryFeedback>(global::Soenneker.Pinecone.OpenApiClient.Models.QueryFeedback.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "input", n => { Input = n.GetCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.QueryInputItem>(global::Soenneker.Pinecone.OpenApiClient.Models.QueryInputItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "max_steps", n => { MaxSteps = n.GetLongValue(); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "object", n => { Object = n.GetStringValue(); } },
                { "output", n => { Output = n.GetCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.QueryOutputItem>(global::Soenneker.Pinecone.OpenApiClient.Models.QueryOutputItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "output_json", n => { OutputJson = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.QueryOutputJsonProperty>(global::Soenneker.Pinecone.OpenApiClient.Models.QueryOutputJsonProperty.CreateFromDiscriminatorValue); } },
                { "previous_query_id", n => { PreviousQueryId = n.GetStringValue(); } },
                { "rollup", n => { Rollup = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.QueryRollup>(global::Soenneker.Pinecone.OpenApiClient.Models.QueryRollup.CreateFromDiscriminatorValue); } },
                { "runtime_ms", n => { RuntimeMs = n.GetLongValue(); } },
                { "session_id", n => { SessionId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "steps", n => { Steps = n.GetCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.QueryStep>(global::Soenneker.Pinecone.OpenApiClient.Models.QueryStep.CreateFromDiscriminatorValue)?.AsList(); } },
                { "synthesis", n => { Synthesis = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.QuerySynthesisComposed>(global::Soenneker.Pinecone.OpenApiClient.Models.QuerySynthesisComposed.CreateFromDiscriminatorValue); } },
                { "thinking_level", n => { ThinkingLevel = n.GetStringValue(); } },
                { "trace_ref", n => { TraceRef = n.GetStringValue(); } },
                { "usage", n => { Usage = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.QueryUsage>(global::Soenneker.Pinecone.OpenApiClient.Models.QueryUsage.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.Citation>("citations", Citations);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.QueryComparisonMember>("comparison", Comparison);
            writer.WriteLongValue("created", Created);
            writer.WriteStringValue("error", Error);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.QueryFeedback>("feedback", Feedback);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.QueryInputItem>("input", Input);
            writer.WriteLongValue("max_steps", MaxSteps);
            writer.WriteStringValue("model", Model);
            writer.WriteStringValue("object", Object);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.QueryOutputItem>("output", Output);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.QueryOutputJsonProperty>("output_json", OutputJson);
            writer.WriteStringValue("previous_query_id", PreviousQueryId);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.QueryRollup>("rollup", Rollup);
            writer.WriteLongValue("runtime_ms", RuntimeMs);
            writer.WriteStringValue("session_id", SessionId);
            writer.WriteStringValue("status", Status);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.QueryStep>("steps", Steps);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.QuerySynthesisComposed>("synthesis", Synthesis);
            writer.WriteStringValue("thinking_level", ThinkingLevel);
            writer.WriteStringValue("trace_ref", TraceRef);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.QueryUsage>("usage", Usage);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
