// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// A restore&apos;s progress: the initial claim, the fetch, the unzip, then periodic staging. `state` is `running` on all four, so key presence is what tells them apart, and only `state` is on every one.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RestoreRunningOutput : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Knowledge files found in the pack. Present once it has been expanded.</summary>
        public long? KnowledgeCount { get; set; }
        /// <summary>The pack archive&apos;s file name. Absent on the staging report.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PackFilename { get; set; }
#nullable restore
#else
        public string PackFilename { get; set; }
#endif
        /// <summary>Byte size of the pack archive. Present once it has been fetched.</summary>
        public long? PackSize { get; set; }
        /// <summary>Source files found in the pack. Present once it has been expanded.</summary>
        public long? SourcesCount { get; set; }
        /// <summary>How far the current phase has got. Absent on the first report, before any phase begins.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutputStageProgress? StageProgress { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutputStageProgress StageProgress { get; set; }
#endif
        /// <summary>When the restore started. Present on the first report only.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartedAt { get; set; }
#nullable restore
#else
        public string StartedAt { get; set; }
#endif
        /// <summary>Always `running`. Which report this is shows in the keys it carries, not here.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? State { get; set; }
#nullable restore
#else
        public string State { get; set; }
#endif
        /// <summary>The context the pack is restored into. Absent on the staging report.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetContextId { get; set; }
#nullable restore
#else
        public string TargetContextId { get; set; }
#endif
        /// <summary>Slug of that target context. Absent from the unzip and staging reports.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TargetSlug { get; set; }
#nullable restore
#else
        public string TargetSlug { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutput"/> and sets the default values.
        /// </summary>
        public RestoreRunningOutput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "knowledge_count", n => { KnowledgeCount = n.GetLongValue(); } },
                { "pack_filename", n => { PackFilename = n.GetStringValue(); } },
                { "pack_size", n => { PackSize = n.GetLongValue(); } },
                { "sources_count", n => { SourcesCount = n.GetLongValue(); } },
                { "stage_progress", n => { StageProgress = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutputStageProgress>(global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutputStageProgress.CreateFromDiscriminatorValue); } },
                { "started_at", n => { StartedAt = n.GetStringValue(); } },
                { "state", n => { State = n.GetStringValue(); } },
                { "target_context_id", n => { TargetContextId = n.GetStringValue(); } },
                { "target_slug", n => { TargetSlug = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("knowledge_count", KnowledgeCount);
            writer.WriteStringValue("pack_filename", PackFilename);
            writer.WriteLongValue("pack_size", PackSize);
            writer.WriteLongValue("sources_count", SourcesCount);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutputStageProgress>("stage_progress", StageProgress);
            writer.WriteStringValue("started_at", StartedAt);
            writer.WriteStringValue("state", State);
            writer.WriteStringValue("target_context_id", TargetContextId);
            writer.WriteStringValue("target_slug", TargetSlug);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
