// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// Specifies which terms must be present in the text of each search hit based on the specified strategy. The match is performedagainst the text field specified in the integrated index `field_map` configuration.Terms are normalized and tokenized into single tokens before matching, and order does not matter.Example:  `&quot;match_terms&quot;: {&quot;terms&quot;: [&quot;animal&quot;, &quot;CHARACTER&quot;, &quot;donald Duck&quot;], &quot;strategy&quot;: &quot;all&quot;}` will tokenize  to `[&quot;animal&quot;, &quot;character&quot;, &quot;donald&quot;, &quot;duck&quot;]`, and would match  `&quot;Donald F. Duck is a funny animal character&quot;` but would not match `&quot;A duck is a funny animal&quot;`.Match terms filtering is supported only for sparse indexes with [integrated embedding](https://docs.pinecone.io/guides/index-data/indexing-overview#vector-embedding)configured to use the [pinecone-sparse-english-v0](https://docs.pinecone.io/models/pinecone-sparse-english-v0) model.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SearchMatchTerms : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The strategy for matching terms in the text. Currently, only `all` is supported, which means all specified terms must be present.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Strategy { get; set; }
#nullable restore
#else
        public string Strategy { get; set; }
#endif
        /// <summary>A list of terms that must be present in the text of each search hit based on the specified strategy.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Terms { get; set; }
#nullable restore
#else
        public List<string> Terms { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.SearchMatchTerms"/> and sets the default values.
        /// </summary>
        public SearchMatchTerms()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.SearchMatchTerms"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.SearchMatchTerms CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.SearchMatchTerms();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "strategy", n => { Strategy = n.GetStringValue(); } },
                { "terms", n => { Terms = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("strategy", Strategy);
            writer.WriteCollectionOfPrimitiveValues<string>("terms", Terms);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
