// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ArchivedFileListing"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.LiveFileListing"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaskFileListing : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ArchivedFileListing"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ArchivedFileListing? ArchivedFileListing { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ArchivedFileListing ArchivedFileListing { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.LiveFileListing"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.LiveFileListing? LiveFileListing { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.LiveFileListing LiveFileListing { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.TaskFileListing"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.TaskFileListing CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Pinecone.OpenApiClient.Models.TaskFileListing();
            if("ArchivedFileListing".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ArchivedFileListing = new global::Soenneker.Pinecone.OpenApiClient.Models.ArchivedFileListing();
            }
            else if("LiveFileListing".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.LiveFileListing = new global::Soenneker.Pinecone.OpenApiClient.Models.LiveFileListing();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ArchivedFileListing != null)
            {
                return ArchivedFileListing.GetFieldDeserializers();
            }
            else if(LiveFileListing != null)
            {
                return LiveFileListing.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ArchivedFileListing != null)
            {
                writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.ArchivedFileListing>(null, ArchivedFileListing);
            }
            else if(LiveFileListing != null)
            {
                writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.LiveFileListing>(null, LiveFileListing);
            }
        }
    }
}
#pragma warning restore CS0618
