// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.CurateManifestTuneOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.CurateNoopOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.CurateRunOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ErrorOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ExploreOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.GroomMetricsOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ImportOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeNoopOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.PackCompletedOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.PackRunningOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEmptyOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEstimateOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.RestoreCompletedOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.SearchCcTurnCompletedOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.SearchTurnCompletedOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.SearchTurnFailedOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.StateFailedOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.StatusErrorOutput"/>, <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.TaskOutputMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TaskOutput : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.CurateManifestTuneOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.CurateManifestTuneOutput? CurateManifestTuneOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.CurateManifestTuneOutput CurateManifestTuneOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.CurateNoopOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.CurateNoopOutput? CurateNoopOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.CurateNoopOutput CurateNoopOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.CurateRunOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.CurateRunOutput? CurateRunOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.CurateRunOutput CurateRunOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ErrorOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ErrorOutput? ErrorOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ErrorOutput ErrorOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ExploreOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ExploreOutput? ExploreOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ExploreOutput ExploreOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.GroomMetricsOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.GroomMetricsOutput? GroomMetricsOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.GroomMetricsOutput GroomMetricsOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ImportOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ImportOutput? ImportOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ImportOutput ImportOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeNoopOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeNoopOutput? OptimizeNoopOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeNoopOutput OptimizeNoopOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutput? OptimizeResultOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutput OptimizeResultOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.PackCompletedOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.PackCompletedOutput? PackCompletedOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.PackCompletedOutput PackCompletedOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.PackRunningOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.PackRunningOutput? PackRunningOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.PackRunningOutput PackRunningOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEmptyOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEmptyOutput? ProfileEmptyOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEmptyOutput ProfileEmptyOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEstimateOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEstimateOutput? ProfileEstimateOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEstimateOutput ProfileEstimateOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.RestoreCompletedOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.RestoreCompletedOutput? RestoreCompletedOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.RestoreCompletedOutput RestoreCompletedOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutput? RestoreRunningOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutput RestoreRunningOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.SearchCcTurnCompletedOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.SearchCcTurnCompletedOutput? SearchCcTurnCompletedOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.SearchCcTurnCompletedOutput SearchCcTurnCompletedOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.SearchTurnCompletedOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.SearchTurnCompletedOutput? SearchTurnCompletedOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.SearchTurnCompletedOutput SearchTurnCompletedOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.SearchTurnFailedOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.SearchTurnFailedOutput? SearchTurnFailedOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.SearchTurnFailedOutput SearchTurnFailedOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.StateFailedOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.StateFailedOutput? StateFailedOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.StateFailedOutput StateFailedOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.StatusErrorOutput"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.StatusErrorOutput? StatusErrorOutput { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.StatusErrorOutput StatusErrorOutput { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.TaskOutputMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.TaskOutputMember1? TaskOutputMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.TaskOutputMember1 TaskOutputMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.TaskOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.TaskOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var result = new global::Soenneker.Pinecone.OpenApiClient.Models.TaskOutput();
            result.CurateManifestTuneOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.CurateManifestTuneOutput();
            result.CurateNoopOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.CurateNoopOutput();
            result.CurateRunOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.CurateRunOutput();
            result.ErrorOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.ErrorOutput();
            result.ExploreOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.ExploreOutput();
            result.GroomMetricsOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.GroomMetricsOutput();
            result.ImportOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.ImportOutput();
            result.OptimizeNoopOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeNoopOutput();
            result.OptimizeResultOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.OptimizeResultOutput();
            result.PackCompletedOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.PackCompletedOutput();
            result.PackRunningOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.PackRunningOutput();
            result.ProfileEmptyOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEmptyOutput();
            result.ProfileEstimateOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.ProfileEstimateOutput();
            result.RestoreCompletedOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.RestoreCompletedOutput();
            result.RestoreRunningOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.RestoreRunningOutput();
            result.SearchCcTurnCompletedOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.SearchCcTurnCompletedOutput();
            result.SearchTurnCompletedOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.SearchTurnCompletedOutput();
            result.SearchTurnFailedOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.SearchTurnFailedOutput();
            result.StateFailedOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.StateFailedOutput();
            result.StatusErrorOutput = new global::Soenneker.Pinecone.OpenApiClient.Models.StatusErrorOutput();
            result.TaskOutputMember1 = new global::Soenneker.Pinecone.OpenApiClient.Models.TaskOutputMember1();
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(CurateManifestTuneOutput != null || CurateNoopOutput != null || CurateRunOutput != null || ErrorOutput != null || ExploreOutput != null || GroomMetricsOutput != null || ImportOutput != null || OptimizeNoopOutput != null || OptimizeResultOutput != null || PackCompletedOutput != null || PackRunningOutput != null || ProfileEmptyOutput != null || ProfileEstimateOutput != null || RestoreCompletedOutput != null || RestoreRunningOutput != null || SearchCcTurnCompletedOutput != null || SearchTurnCompletedOutput != null || SearchTurnFailedOutput != null || StateFailedOutput != null || StatusErrorOutput != null || TaskOutputMember1 != null)
            {
                return ParseNodeHelper.MergeDeserializersForIntersectionWrapper(CurateManifestTuneOutput, CurateNoopOutput, CurateRunOutput, ErrorOutput, ExploreOutput, GroomMetricsOutput, ImportOutput, OptimizeNoopOutput, OptimizeResultOutput, PackCompletedOutput, PackRunningOutput, ProfileEmptyOutput, ProfileEstimateOutput, RestoreCompletedOutput, RestoreRunningOutput, SearchCcTurnCompletedOutput, SearchTurnCompletedOutput, SearchTurnFailedOutput, StateFailedOutput, StatusErrorOutput, TaskOutputMember1);
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.CurateManifestTuneOutput>(null, CurateManifestTuneOutput, CurateNoopOutput, CurateRunOutput, ErrorOutput, ExploreOutput, GroomMetricsOutput, ImportOutput, OptimizeNoopOutput, OptimizeResultOutput, PackCompletedOutput, PackRunningOutput, ProfileEmptyOutput, ProfileEstimateOutput, RestoreCompletedOutput, RestoreRunningOutput, SearchCcTurnCompletedOutput, SearchTurnCompletedOutput, SearchTurnFailedOutput, StateFailedOutput, StatusErrorOutput, TaskOutputMember1);
        }
    }
}
#pragma warning restore CS0618
