// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// One reasoning step as recorded in the trace — its generated code, tool calls, strategy, and cost. Every field is optional; a step carries what its stage produced.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TraceStep : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The tool calls this step made.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.TraceCall>? Calls { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Pinecone.OpenApiClient.Models.TraceCall> Calls { get; set; }
#endif
        /// <summary>A step&apos;s generated code, capped. Either the source string alone or a `{language, source}` document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.StepCode? Code { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.StepCode Code { get; set; }
#endif
        /// <summary>The model&apos;s own one-line account of what this step is doing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Commentary { get; set; }
#nullable restore
#else
        public string Commentary { get; set; }
#endif
        /// <summary>The step&apos;s incremental token and latency cost — deltas against the running turn cursor, not totals. The cache fields are tracked only on the search-as-code path.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.StepCost? Cost { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.StepCost Cost { get; set; }
#endif
        /// <summary>Identifies the step within the turn.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StepId { get; set; }
#nullable restore
#else
        public string StepId { get; set; }
#endif
        /// <summary>The retrieval approach the step picked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Pinecone.OpenApiClient.Models.StepStrategy? Strategy { get; set; }
#nullable restore
#else
        public global::Soenneker.Pinecone.OpenApiClient.Models.StepStrategy Strategy { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.TraceStep"/> and sets the default values.
        /// </summary>
        public TraceStep()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.TraceStep"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.TraceStep CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.TraceStep();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "calls", n => { Calls = n.GetCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.TraceCall>(global::Soenneker.Pinecone.OpenApiClient.Models.TraceCall.CreateFromDiscriminatorValue)?.AsList(); } },
                { "code", n => { Code = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.StepCode>(global::Soenneker.Pinecone.OpenApiClient.Models.StepCode.CreateFromDiscriminatorValue); } },
                { "commentary", n => { Commentary = n.GetStringValue(); } },
                { "cost", n => { Cost = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.StepCost>(global::Soenneker.Pinecone.OpenApiClient.Models.StepCost.CreateFromDiscriminatorValue); } },
                { "step_id", n => { StepId = n.GetStringValue(); } },
                { "strategy", n => { Strategy = n.GetObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.StepStrategy>(global::Soenneker.Pinecone.OpenApiClient.Models.StepStrategy.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Pinecone.OpenApiClient.Models.TraceCall>("calls", Calls);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.StepCode>("code", Code);
            writer.WriteStringValue("commentary", Commentary);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.StepCost>("cost", Cost);
            writer.WriteStringValue("step_id", StepId);
            writer.WriteObjectValue<global::Soenneker.Pinecone.OpenApiClient.Models.StepStrategy>("strategy", Strategy);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
