// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Models
{
    /// <summary>
    /// The step&apos;s incremental cost (deltas against the running turn cursor).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TraceStepCost : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The decide_ms property</summary>
        public long? DecideMs { get; set; }
        /// <summary>The execute_ms property</summary>
        public long? ExecuteMs { get; set; }
        /// <summary>The tokens_in property</summary>
        public long? TokensIn { get; set; }
        /// <summary>The tokens_in_cached property</summary>
        public long? TokensInCached { get; set; }
        /// <summary>The tokens_in_cache_write property</summary>
        public long? TokensInCacheWrite { get; set; }
        /// <summary>The tokens_in_fresh property</summary>
        public long? TokensInFresh { get; set; }
        /// <summary>The tokens_out property</summary>
        public long? TokensOut { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.TraceStepCost"/> and sets the default values.
        /// </summary>
        public TraceStepCost()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.TraceStepCost"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Pinecone.OpenApiClient.Models.TraceStepCost CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Pinecone.OpenApiClient.Models.TraceStepCost();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "decide_ms", n => { DecideMs = n.GetLongValue(); } },
                { "execute_ms", n => { ExecuteMs = n.GetLongValue(); } },
                { "tokens_in", n => { TokensIn = n.GetLongValue(); } },
                { "tokens_in_cache_write", n => { TokensInCacheWrite = n.GetLongValue(); } },
                { "tokens_in_cached", n => { TokensInCached = n.GetLongValue(); } },
                { "tokens_in_fresh", n => { TokensInFresh = n.GetLongValue(); } },
                { "tokens_out", n => { TokensOut = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("decide_ms", DecideMs);
            writer.WriteLongValue("execute_ms", ExecuteMs);
            writer.WriteLongValue("tokens_in", TokensIn);
            writer.WriteLongValue("tokens_in_cached", TokensInCached);
            writer.WriteLongValue("tokens_in_cache_write", TokensInCacheWrite);
            writer.WriteLongValue("tokens_in_fresh", TokensInFresh);
            writer.WriteLongValue("tokens_out", TokensOut);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
