// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pinecone.OpenApiClient.Nexus_data.Contexts.Item.Knowledge.Read.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Nexus_data.Contexts.Item.Knowledge.Read
{
    /// <summary>
    /// Builds and executes requests for operations under \nexus_data\contexts\{slug}\knowledge\read
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReadRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Pinecone.OpenApiClient.nexus_data.contexts.item.knowledge.read.item collection</summary>
        /// <param name="position">Relative path within the tree. Matches greedily, so it may contain `/`.</param>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Contexts.Item.Knowledge.Read.Item.WithPathItemRequestBuilder"/></returns>
        public global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Contexts.Item.Knowledge.Read.Item.WithPathItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("path", position);
                return new global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Contexts.Item.Knowledge.Read.Item.WithPathItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Contexts.Item.Knowledge.Read.ReadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReadRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/nexus_data/contexts/{slug}/knowledge/read", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Contexts.Item.Knowledge.Read.ReadRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReadRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/nexus_data/contexts/{slug}/knowledge/read", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
