// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pinecone.OpenApiClient.Models;
using Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks
{
    /// <summary>
    /// Builds and executes requests for operations under \nexus_data\tasks
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TasksRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Pinecone.OpenApiClient.nexus_data.tasks.item collection</summary>
        /// <param name="position">Task id.</param>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.Item.TasksItemRequestBuilder"/></returns>
        public global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.Item.TasksItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("id", position);
                return new global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.Item.TasksItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.TasksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/nexus_data/tasks{?context*,limit*,offset*,page*,q*,state*,workflow*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.TasksRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TasksRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/nexus_data/tasks{?context*,limit*,offset*,page*,q*,state*,workflow*}", rawUrl)
        {
        }
        /// <summary>
        /// Task records across the project, newest first. Filter by workflow, state, or context, and page with `limit` plus `page` or `offset`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.TaskList"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Pinecone.OpenApiClient.Models.TaskList?> GetAsync(Action<RequestConfiguration<global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Pinecone.OpenApiClient.Models.TaskList> GetAsync(Action<RequestConfiguration<global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Pinecone.OpenApiClient.Models.TaskList>(requestInfo, global::Soenneker.Pinecone.OpenApiClient.Models.TaskList.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Task records across the project, newest first. Filter by workflow, state, or context, and page with `limit` plus `page` or `offset`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.TasksRequestBuilder.TasksRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.TasksRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.TasksRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Pinecone.OpenApiClient.Nexus_data.Tasks.TasksRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Task records across the project, newest first. Filter by workflow, state, or context, and page with `limit` plus `page` or `offset`.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class TasksRequestBuilderGetQueryParameters 
        {
            /// <summary>Context slug or UUID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("context")]
            public string? Context { get; set; }
#nullable restore
#else
            [QueryParameter("context")]
            public string Context { get; set; }
#endif
            /// <summary>Maximum tasks per page.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            /// <summary>Where the page starts. Takes precedence over `page`.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>1-based page to return. Ignored when `offset` is given.</summary>
            [QueryParameter("page")]
            public int? Page { get; set; }
            /// <summary>Free-text over id/created_by/input</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("q")]
            public string? Q { get; set; }
#nullable restore
#else
            [QueryParameter("q")]
            public string Q { get; set; }
#endif
            /// <summary>Return only tasks in this state.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("state")]
            public string? State { get; set; }
#nullable restore
#else
            [QueryParameter("state")]
            public string State { get; set; }
#endif
            /// <summary>Return only tasks of this workflow.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("workflow")]
            public string? Workflow { get; set; }
#nullable restore
#else
            [QueryParameter("workflow")]
            public string Workflow { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
