// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pinecone.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Context
{
    /// <summary>
    /// Builds and executes requests for operations under \assistant_data\chat\{assistant_name}\context
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ContextRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Context.ContextRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContextRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assistant_data/chat/{assistant_name}/context", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Context.ContextRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ContextRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assistant_data/chat/{assistant_name}/context", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve context snippets from an assistant to use as part of RAG or any agentic flow.For guidance and examples, see [Retrieve context snippets](https://docs.pinecone.io/guides/assistant/retrieve-context-snippets).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Models.ContextModel"/></returns>
        /// <param name="body">Parameters to retrieve context from an assistant.</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.AssistantData202604ErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.AssistantData202604ErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.AssistantData202604ErrorResponse">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Pinecone.OpenApiClient.Models.AssistantData202604ErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Pinecone.OpenApiClient.Models.ContextModel?> PostAsync(global::Soenneker.Pinecone.OpenApiClient.Models.ContextRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Pinecone.OpenApiClient.Models.ContextModel> PostAsync(global::Soenneker.Pinecone.OpenApiClient.Models.ContextRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Pinecone.OpenApiClient.Models.AssistantData202604ErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Pinecone.OpenApiClient.Models.AssistantData202604ErrorResponse.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Pinecone.OpenApiClient.Models.AssistantData202604ErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Pinecone.OpenApiClient.Models.AssistantData202604ErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Pinecone.OpenApiClient.Models.ContextModel>(requestInfo, global::Soenneker.Pinecone.OpenApiClient.Models.ContextModel.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve context snippets from an assistant to use as part of RAG or any agentic flow.For guidance and examples, see [Retrieve context snippets](https://docs.pinecone.io/guides/assistant/retrieve-context-snippets).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">Parameters to retrieve context from an assistant.</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Pinecone.OpenApiClient.Models.ContextRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Pinecone.OpenApiClient.Models.ContextRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Context.ContextRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Context.ContextRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Context.ContextRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
