// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Chat.Completions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Chat
{
    /// <summary>
    /// Builds and executes requests for operations under \assistant_data\chat\{assistant_name}\chat
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ChatRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The completions property</summary>
        public global::Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Chat.Completions.CompletionsRequestBuilder Completions
        {
            get => new global::Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Chat.Completions.CompletionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Chat.ChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChatRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assistant_data/chat/{assistant_name}/chat", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Assistant_data.Chat.Item.Chat.ChatRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ChatRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assistant_data/chat/{assistant_name}/chat", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
