// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pinecone.OpenApiClient.Db_data_202604.Records.Namespaces.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Db_data_202604.Records.Namespaces
{
    /// <summary>
    /// Builds and executes requests for operations under \db_data_2026-04\records\namespaces
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NamespacesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Pinecone.OpenApiClient.db_data_202604.records.namespaces.item collection</summary>
        /// <param name="position">The namespace to upsert records into.</param>
        /// <returns>A <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_data_202604.Records.Namespaces.Item.WithNamespaceItemRequestBuilder"/></returns>
        public global::Soenneker.Pinecone.OpenApiClient.Db_data_202604.Records.Namespaces.Item.WithNamespaceItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("namespace", position);
                return new global::Soenneker.Pinecone.OpenApiClient.Db_data_202604.Records.Namespaces.Item.WithNamespaceItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_data_202604.Records.Namespaces.NamespacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NamespacesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/db_data_2026-04/records/namespaces", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Db_data_202604.Records.Namespaces.NamespacesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NamespacesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/db_data_2026-04/records/namespaces", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
