// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Chat;
using Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Files;
using Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Operations;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Pinecone.OpenApiClient.Assistant_data_202604
{
    /// <summary>
    /// Builds and executes requests for operations under \assistant_data_2026-04
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Assistant_data_202604RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The chat property</summary>
        public global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Chat.ChatRequestBuilder Chat
        {
            get => new global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Chat.ChatRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The operations property</summary>
        public global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Operations.OperationsRequestBuilder Operations
        {
            get => new global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Operations.OperationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Assistant_data_202604RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Assistant_data_202604RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assistant_data_2026-04", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Pinecone.OpenApiClient.Assistant_data_202604.Assistant_data_202604RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public Assistant_data_202604RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/assistant_data_2026-04", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
